// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1, arg2, arg3) {
  return window['go']['main']['TaskManager']['AddTask'](arg1, arg2, arg3);
}

export function DeleteTask(arg1) {
  return window['go']['main']['TaskManager']['DeleteTask'](arg1);
}

export function GetAllTasks() {
  return window['go']['main']['TaskManager']['GetAllTasks']();
}

export function ToggleTaskCompletion(arg1) {
  return window['go']['main']['TaskManager']['ToggleTaskCompletion'](arg1);
}
